[versions]

[libraries]
spring-doc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version = "2.5.0" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }

h2 = { module = "com.h2database:h2" }
postgresql = { module = "org.postgresql:postgresql" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.0" }
dependency-management = { id = "io.spring.dependency-management", version = "1.1.5" }
lombok = { id = "io.freefair.lombok", version = "8.6" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
